#!/usr/bin/env bash
set -euo pipefail

OUTPUT_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/cargo/packages.toml"

# tmpfile="$(mktemp)"
{
  echo "# This file is auto-generated by generate-cargo-packages.sh"
  echo "# Do not edit manually unless you know what you're doing."
  echo
  echo "[packages]"
  echo "tools = ["

  cargo install --list \
    | awk '
      /^[a-zA-Z0-9._-]+ v[0-9]/ {
        name=$1
        version=$2
        sub(/^v/, "", version)
        sub(/:$/, "", version)
        printf "  \"%s@%s\",\n", name, version
      }
    ' \
    | sort

  echo "]"
} > "$OUTPUT_FILE"

chmod +r "$OUTPUT_FILE"
chezmoi add "$OUTPUT_FILE"
